### ISSUE TITLE
Request Status Info

### ISSUE THREAD

**Issue by lorendias** [Xaviju/rethinkscape-gtk3#1]
I am wondering if there is any status update on this? This layout is absolutely beautiful and if there ever becomes a GIT repo where I can run it - I would like to use it on day 1.

Is there a order of things that need to preceed it? Suchas a complete GTK3 port. I presume that if the Interface and Core are reasonable seperated in GTK that a changeout from one layout to another would be a lot easier to achieve.

**Comment by Xaviju** [comment]
Hi @lorendias 
The goal of this repo is to experiment with UI/UX sugestions to Inkscape devs using GTK components and Gnome Guidelines. Currently Inkscape is moving towards the separation of layout and logic and maybe in the future this would be possible.
